name: Generate Snake

# Controls when the action will run. This action runs every 6 hours and can also be manually triggered.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Check out the repository to the runner
      - name: Checkout Repository
        uses: actions/checkout@v2

      # snake GIF and SVG generation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Mchiir
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Showed the status of the build (useful for debugging)
      - name: Check Git Status
        run: git status

      # Pushed generated snake files to the main branch
      - name: Push Snake to Main Branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # default branch used
          force: true

      # Deployed the generated files to GitHub Pages on the output branch
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # set default output branch
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
